# 01 - Raw Data Understanding

The purpose of this document is to get a better undestanding of the raw data, the feature structure, the target distribution, the data format, etc.

## Setting up Project Directory

In [1]:
from jupyter_init import setup
setup()

## Loading Data

In [2]:
from src_code.config import JIT_TRAIN_FEATHER_FILE, JIT_TEST_FEATHER_FILE, JIT_VAL_FEATHER_FILE
import pandas as pd


df = pd.read_feather(JIT_TRAIN_FEATHER_FILE)
df_test = pd.read_feather(JIT_TEST_FEATHER_FILE)
df_val = pd.read_feather(JIT_VAL_FEATHER_FILE)

df_len = len(df)
def_len_total = df_len + len(df_test) + len(df_val)
print(f"Loaded df with size {df_len}")
print(f"Total size of all dataframes: {def_len_total}")

Loaded df with size 185369
Total size of all dataframes: 205369

In [3]:

df[df['commit'] == '99a30f8fdb19ce7ebc688ac36188271070fb023d']

,datetime,commit,repo,filepath,content,methods,lines
9532,2017-06-02 07:45:50-02:00,99a30f8fdb19ce7ebc688ac36188271070fb023d,ansible,lib\ansible\plugins\inventory\__init__.py,"@@ -61,11 +61,11 @@ class BaseInventoryPlugin(...",[get_cache_prefix],"[64, 68]"

In [4]:
# df[['commit', 'repo', 'induce_bug']].head()
df[df['lines'].apply(lambda x: len(x) == 0)]

,datetime,commit,repo,filepath,content,methods,lines
2,2019-03-15 17:14:46-02:00,00842d7f1b20cfc8994717098b06b5f0d9fa566d,spaCy,spacy\cli\converters\__init__.py,"@@ -1,5 +1,4 @@\n from .conllu2json import con...",[],[]
6,2012-10-11 15:03:28-02:00,04b0027e64e6b1ec6211ff67e86128c8fe1eeed4,celery,celery\apps\worker.py,"@@ -102,7 +102,6 @@ class Worker(WorkControlle...",[on_init_namespace],[]
8,2020-11-03 11:04:40-02:00,007634fd1b7f52d6418043b52e01141f72d5d6b4,ray,python\ray\tune\config_parser.py,"@@ -193,6 +193,5 @@ def create_trial_from_spec...",[create_trial_from_spec],[]
10,2016-02-12 06:01:25-02:00,004ba0f99eb25c3f32aa3a41707534e955d1878e,django,django\contrib\contenttypes\admin.py,"@@ -33,7 +33,6 @@ class GenericInlineModelAdmi...",[_check_relation],[]
12,2019-10-02 04:07:41-02:00,00622ec1d53bc2261a424f4f22c3d3c37859e368,sentry,src\sentry\conf\server.py,"@@ -816,8 +816,6 @@ SENTRY_FEATURES = {\n ...",[],[]
...,...,...,...,...,...,...,...
43560,2016-12-08 04:32:25-02:00,f9b85306f0df8e1f049582af1de382555dee1510,ansible,lib\ansible\modules\extras\system\facter.py,"@@ -45,7 +45,7 @@ def main():\n argume...",[main],[]
43561,2017-05-16 05:10:15-02:00,668092e95ac1f0be79d531753b8856d790c4cfca,ansible,lib\ansible\modules\cloud\amazon\elasticache_s...,"@@ -71,8 +71,7 @@ EXAMPLES = '''\n \n try:\n ...",[main],[]
43562,2019-06-06 21:29:19-02:00,a87de8d7b012ca5962a0be2ba21d6b2708ce9392,ansible,lib\ansible\modules\network\vyos\vyos_interfac...,"@@ -227,7 +227,7 @@ def map_obj_to_commands(up...",[map_config_to_obj],[]
43563,2019-06-06 21:29:19-02:00,a87de8d7b012ca5962a0be2ba21d6b2708ce9392,ansible,lib\ansible\plugins\cliconf\vyos.py,"@@ -71,10 +71,18 @@ class Cliconf(CliconfBase)...",[get_config],[]
43564,2015-05-01 07:57:13-02:00,8d324e6a50459641fb654e4b921ebb8418a6643d,ansible,lib\ansible\cache\jsonfile.py,"@@ -108,6 +108,7 @@ class CacheModule(BaseCach...",[contains],[]

In [5]:
print(f"Size: {len(df)}")

Size: 185369

In [6]:
df[df['filepath'] == 'pandas\\core\\indexes\\base.py']

,datetime,commit,repo,filepath,content,methods,lines
177,2021-11-11 15:19:05-02:00,01b86edbbbf4bd81d85d7d6638117545cd13dfac,pandas,pandas\core\indexes\base.py,"@@ -399,7 +399,7 @@ class Index(IndexOpsMixin,...","[_maybe_cast_data_without_dtype, set_value, __...","[402, 635, 749, 922, 1194, 1374, 2506, 2541, 2..."
207,2020-02-21 23:53:08-02:00,020dcce17e3bd0983fca5b02556bd431140ab371,pandas,pandas\core\indexes\base.py,"@@ -3111,7 +3111,7 @@ class Index(IndexOpsMixi...",[_convert_scalar_indexer],[3114]
226,2021-07-01 13:12:44-02:00,0283df65e57df0601972fa7aa3c8a1b130afbe74,pandas,pandas\core\indexes\base.py,"@@ -3440,7 +3440,7 @@ class Index(IndexOpsMixi...","[_should_partial_index, get_indexer]","[3443, 3522, 3523, 3524, 3525, 3526, 3527, 352..."
228,2018-08-06 00:36:29-02:00,028492d04bd500995621931ad1c985bbe8865956,pandas,pandas\core\indexes\base.py,"@@ -2463,7 +2463,7 @@ class Index(IndexOpsMixi...",[asof_locs],[2466]
241,2020-07-07 03:19:59-02:00,031fb16835af1f92522649d0b1f53808c5d9338c,pandas,pandas\core\indexes\base.py,"@@ -2,7 +2,16 @@ from copy import copy as copy...","[_format_with_header, trim_front, _format_with...","[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 922, 925, ..."
...,...,...,...,...,...,...,...
15341,2018-12-10 05:59:26-02:00,91802fb0accde031c3b6aca040a8b533a193fef6,pandas,pandas\core\indexes\base.py,"@@ -4281,7 +4281,8 @@ class Index(IndexOpsMixi...",[get_value],[]
15347,2019-03-30 09:08:51-02:00,27927056b368fa8c9501c4ec8729546dbe98068c,pandas,pandas\core\indexes\base.py,"@@ -3630,8 +3630,7 @@ class Index(IndexOpsMixi...",[_values],[]
15403,2021-06-17 07:51:36-02:00,9fd7d13d9b94f18f21ff0922884dd67dc034688d,pandas,pandas\core\indexes\base.py,"@@ -3091,7 +3091,7 @@ class Index(IndexOpsMixi...","[_wrap_intersection_result, intersection]",[]
15439,2021-03-30 02:56:56-02:00,f625cb42b471dbfdd42604b421862737394981d6,pandas,pandas\core\indexes\base.py,"@@ -2663,7 +2663,7 @@ class Index(IndexOpsMixi...",[duplicated],[]
15572,2020-10-29 11:46:28-02:00,2414c75bfe06064a95d8da4db5c8248e5aa0cdbb,pandas,pandas\core\indexes\base.py,"@@ -5208,7 +5208,9 @@ class Index(IndexOpsMixi...",[get_slice_bound],[]

In [7]:
df_filtered = df[df['commit'] == 'fb797a9e7786a3fde70e7de34ccf9ac3946501b3']
df_filtered[['commit', 'repo', 'lines']]

,commit,repo,lines
15270,fb797a9e7786a3fde70e7de34ccf9ac3946501b3,ansible,"[52, 106, 107, 218, 221, 222, 223, 224, 225, 2..."
15271,fb797a9e7786a3fde70e7de34ccf9ac3946501b3,ansible,"[326, 340, 341, 347, 349, 350, 351, 352, 353]"

## Repo Proportion

In [8]:
print(df['repo'].value_counts(normalize=True))

repo
ansible                  0.231031
sentry                   0.172402
core                     0.157205
pandas                   0.078314
ray                      0.065852
django                   0.059487
lightning                0.043724
airflow                  0.043119
cpython                  0.038205
scikit-learn             0.026099
celery                   0.018638
spaCy                    0.012758
poetry                   0.009284
localstack               0.007148
transformers             0.006668
openpilot                0.005702
numpy                    0.005227
yolov5                   0.004386
redash                   0.003884
jax                      0.003566
black                    0.002390
scrapy                   0.002239
django-rest-framework    0.002174
pipenv                   0.000491
freqtrade                0.000005
Name: proportion, dtype: float64

In [9]:
df.dtypes
print(df_test['repo'].value_counts(normalize=True))

repo
sentry          0.2341
ray             0.1899
lightning       0.1767
core            0.1751
airflow         0.0652
pandas          0.0494
ansible         0.0226
openpilot       0.0158
poetry          0.0132
transformers    0.0130
localstack      0.0126
yolov5          0.0092
django          0.0070
scikit-learn    0.0062
cpython         0.0034
spaCy           0.0032
black           0.0016
jax             0.0012
pipenv          0.0005
celery          0.0001
Name: proportion, dtype: float64

## Empty Methods Check

In [10]:
# df['methods'].info()
# Count empty lists
empty_count = df['methods'].apply(lambda x: len(x) == 0).sum()

# Percentage of empty lists
empty_percent = df['methods'].apply(lambda x: len(x) == 0).mean() * 100

print(empty_count, empty_percent)

52218 28.169758697516844